### ISSUE TITLE
Add `createdAt` and `updatedAt` columns for the Student table

### ISSUE THREAD

**Issue by aryanprince** [UniTrackApp/dashboard#51]
First we'll add them to `Student` table before adding them to other tables

This will let us 'sort' items by creation or update times. When our UI has sort and filter options, would be nice to be able to sort by creation time descending for example which would show new students created at top for easy management.

**Comment by lewisj576** [comment]
https://www.prisma.io/docs/concepts/components/prisma-schema/data-model#:~:text=())-,createdAt%20%20DateTime%20%20%20%40default(now()),-updatedAt%20%20DateTime%20%20%20%40updatedAt

![image](https://github.com/UniTrackApp/dashboard/assets/84625224/0c823884-0286-4957-b20c-8928d57dd4a5)

**Comment by aryanprince** [comment]
@lewisj576 Alright, sounds good :)
