### ISSUE TITLE
Create AttendanceRecord Next.js API route (for client scanner)

### ISSUE THREAD

**Issue by aryanprince** [UniTrackApp/dashboard#87]
## Step-by-step workflow

- [x] Client sends `studentCardId` and `lectureId` to server
- [x] Server checks if `studentId` exists for the `studentCardId`
_(error if the card isn't registered)_
- [x] Check what's the `moduleId` for the given `lectureId` 
_(error if doesn't exist)_
- [x]  Compare `moduleId` and `studentId` from `Enrollment` table to see if student belongs in that lecture 
_(error if false)_
- [x]  Check the `lectureStartTime` and compare it with current time to find which `AttendanceStatus` it gets
_(error if tap beyond class end time)_
- [ ] Create an `AttendanceRecord` with the following new info: 

- `attendanceRecordId` (default CUID)
- `studentId`
- `lectureId`
- `status` (calculated from step 5)
- `timestamp` (default, don't manually add)

**Comment by aryanprince** [comment]
@lewisj576 We can also have an initial check in the beginning to see if a student already has an AttendanceRecord for a given lecture already, if yes, we skip.

For example: Aryan taps card, gets a record created. Aryan taps again, it check Aryan already has a record for this lecture, shows error.

**Comment by Bosurgi** [comment]
We can just do an initial check like this pseudo code?

if StudentID in AttendanceRecordTable:
    return Response.Status(400)
@aryanprince @lewisj576

**Comment by aryanprince** [comment]
Yes exactly! 

We would have to check if there is an AttendanceRecord with given `studentId` and `lectureId` too, cus Aryan can attend other lectures as well.
